# Generated by Django 2.0.1 on 2018-09-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='email_contact',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
