# Generated by Django 2.0.1 on 2018-09-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contactmodel_email_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='client',
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='phone_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
